version: '3'

services:

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass redis
    # volumes:
    #    - redis-data:/data

  memcached:
    image: memcached:latest
    ports:
     - "11211:11211"
