version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass redis
    # volumes:
    #    - redis-data:/data
  memcached:
    image: memcached:latest
    ports:
     - "11211:11211"

  mysql:
      build: ./mysql/
      volumes:
        - ./mysql/mysql_data:/var/lib/mysql # データの永続化
        - ./mysql/sqls:/docker-entrypoint-initdb.d # 初期データ投入
      environment:
        - MYSQL_ROOT_PASSWORD=root #rootパスワードの設定
      ports:
       - "33060:3306"

#  mysql:
#    image: mysql:5.7
#    ports:
#     - "33060:3306"
#    command: mysqld
